# Enhanced docker-compose.yml
version: '3.8'

services:
  # PostgreSQL with PGVector
  postgres:
    image: pgvector/pgvector:pg16
    container_name: aims_postgres
    environment:
      POSTGRES_DB: aims_memory
      POSTGRES_USER: aims
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-aims_secure_password}
      POSTGRES_MAX_CONNECTIONS: 200
      POSTGRES_SHARED_BUFFERS: 2GB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 6GB
      POSTGRES_WORK_MEM: 256MB
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aims"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: aims_redis
    command: >
      redis-server 
      --maxmemory 4gb 
      --maxmemory-policy allkeys-lru
      --appendonly yes
      --appendfsync everysec
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Qdrant vector database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: aims_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"  # gRPC port
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__LOG_LEVEL=INFO
    restart: unless-stopped

  # Neo4j (optional - for knowledge graphs)
  neo4j:
    image: neo4j:5.15-enterprise
    container_name: aims_neo4j
    environment:
      - NEO4J_AUTH=neo4j/aims_secure_password
      - NEO4J_PLUGINS=["graph-data-science", "apoc"]
      - NEO4J_server_memory_heap_initial__size=2G
      - NEO4J_server_memory_heap_max__size=4G
      - NEO4J_server_memory_pagecache__size=2G
    volumes:
      - neo4j_data:/data
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    profiles:
      - full  # Only start with --profile full
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  qdrant_data:
  neo4j_data:

networks:
  default:
    name: aims_network
    driver: bridge