version: '3.8'

services:
  # PostgreSQL with PGVector
  postgres:
    image: pgvector/pgvector:pg16
    container_name: aims_postgres
    environment:
      POSTGRES_DB: aims_memory
      POSTGRES_USER: aims
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-aims_secure_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aims"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: aims_redis
    command: redis-server --maxmemory 2gb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Qdrant vector database
  qdrant:
    image: qdrant/qdrant
    container_name: aims_qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334

volumes:
  postgres_data:
  redis_data:
  qdrant_data:

networks:
  default:
    name: aims_network
