api:
  claude:
    model: "claude-3-opus-20240229"
    max_tokens: 4096
    temperature_base: 0.7

consciousness:
  working_memory_size: 10
  cycle_frequency: 1.0
  coherence_threshold: 0.5

memory:
  redis_url: "redis://localhost:6379"
  postgres_url: "postgresql+asyncpg://aims:aims_password@localhost:5432/aims_memory"
  chroma_persist_dir: "./data/chroma"
  ttl_seconds: 300

state_management:
  state_path: "./data/states"
  backup_path: "./data/backups"
  backup_interval_hours: 6
  max_local_backups: 7
  compression: true

websocket:
  host: "localhost"
  port: 8765
  update_interval: 0.5
  ping_interval: 30.0